<a href="https://colab.research.google.com/github/MysticKrameNine/AI-Pacman/blob/master/neuro_symbolic_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import time



In [27]:
n = np.linspace(0,1,5)
t = torch.linspace(0,1,5)

In [28]:
n = np.arange(48).reshape(3,4,4)
t = torch.arange(48).reshape(3,4,4)

In [29]:
a = np.ones((6,5))
b = np.arange(5).reshape((1,5))

In [30]:
a+b


array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [31]:
a = torch.ones((6,5))
b = torch.arange(5).reshape((1,5))

In [32]:
Image = torch.randn((256,256,3))
Scale = torch.tensor([0.5,1.5,1])

In [33]:
Result = Image*Scale

In [34]:
Images = torch.randn((2,256,256,3))
Scales = torch.tensor([0.5,1.5,1,1.5,1,0.5]).reshape((2,1,1,3))

In [35]:
t = torch.tensor([0.5,1,3,4])
torch.mean(t), torch.std(t), torch.max(t), torch.min(t)

(tensor(2.1250), tensor(1.6520), tensor(4.), tensor(0.5000))

In [36]:
t = torch.arange(20, dtype=float).reshape(5,4)

In [37]:
t = torch.arange(20, dtype=float).reshape(5,4)
torch.mean(t, axis=0)

tensor([ 8.,  9., 10., 11.], dtype=torch.float64)

In [38]:
t = torch.randn(5,256,256,3)

In [39]:
torch.mean(t,axis=0).shape

torch.Size([256, 256, 3])

In [40]:
values, indices = torch.max(t,axis=-1)

In [41]:
x = torch.tensor([[5.,8.],[4.,6.]], requires_grad=True)

In [42]:
x = torch.tensor([[5.,8.],[4.,6.]], requires_grad=True)
y = x.pow(3).sum()
y

tensor(917., grad_fn=<SumBackward0>)

In [43]:
y.backward() #compute the gradient
x.grad #print the gradient (everything that has happened to x)

tensor([[ 75., 192.],
        [ 48., 108.]])

In [44]:
3*x**2

tensor([[ 75., 192.],
        [ 48., 108.]], grad_fn=<MulBackward0>)

In [45]:
A = torch.randn((1000,1000))
B = torch.randn((1000,1000))

In [46]:
t1 = time.perf_counter()
torch.matmul(A,B)
t2 = time.perf_counter()
print(t2-t1)

0.03999166100004459


In [47]:
A = np.random.randn(int(1e6)).reshape((1000,1000))
B = np.random.randn(int(1e6)).reshape((1000,1000))

In [48]:
t1 = time.perf_counter()
A@B
t2 = time.perf_counter()
print(t2-t1)

0.07139284000004409
